/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class main extends javax.swing.JFrame {

    ArrayList<Equipo> equipos = new ArrayList(); //ArrayList de equipos
    DecimalFormat df = new DecimalFormat("#.00"); //Formato de los decimales que se utilizara mas adelante con el manejo de los pesos
    Torneo torneo = null; //Objeto de Torneo utilizado para manejar el torneo unico con 2 jornadas dentro del sistema de quinela

    public main() throws IOException {

        //Cargar componentes externos del Jframe
        this.setLocationRelativeTo(null);
        this.setIconImage(ImageIO.read(new File("./src/Pics/iconframe.png")));

        
        /**
         * Cargar los Equipos en el arraylist de <equipo>
         */
        File file = null;
        BufferedReader br = null;
        FileReader fr = null;

        try {
            file = new File("./src/Data/Equipos.txt");
            fr = new FileReader(file);
            br = new BufferedReader(fr);

            String nombre = "";

            while ((nombre = br.readLine()) != null) {
                Equipo eq = new Equipo(nombre);
                equipos.add(eq);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            br.close();
            fr.close();
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Administracion_Dialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_ModificarTorneo = new javax.swing.JButton();
        btn_VisualizarTorneo = new javax.swing.JButton();
        btn_BorrarTorneo = new javax.swing.JButton();
        btn_CrearTorneo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        VisualizarTorneo_Dia = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaJornadaA = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_SalirVisualizacionTorneo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaJornadaB = new javax.swing.JTable();
        User_Main = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        btn_VerEquipos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        label_NumJornadaUser_Main = new javax.swing.JLabel();
        MenuApuestas = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        label_NumJornadaMenuApuestas = new javax.swing.JLabel();
        rb_EquipoA = new javax.swing.JRadioButton();
        rb_Empate = new javax.swing.JRadioButton();
        rb_EquipoB = new javax.swing.JRadioButton();
        btn_SiguentePartido = new javax.swing.JButton();
        Dialog_IngresarApuesta = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        tf_MontoApuesta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btn_admin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_quinela = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        Administracion_Dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel3.setText("Administración");

        btn_ModificarTorneo.setText("Modificar Torneo");

        btn_VisualizarTorneo.setText("Visualizar Torneo");
        btn_VisualizarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VisualizarTorneoActionPerformed(evt);
            }
        });

        btn_BorrarTorneo.setText("Borrar Torneo");
        btn_BorrarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarTorneoActionPerformed(evt);
            }
        });

        btn_CrearTorneo.setText("Crear Torneo");
        btn_CrearTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearTorneoActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Administracion_DialogLayout = new javax.swing.GroupLayout(Administracion_Dialog.getContentPane());
        Administracion_Dialog.getContentPane().setLayout(Administracion_DialogLayout);
        Administracion_DialogLayout.setHorizontalGroup(
            Administracion_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Administracion_DialogLayout.createSequentialGroup()
                .addGroup(Administracion_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Administracion_DialogLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3))
                    .addGroup(Administracion_DialogLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Administracion_DialogLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(Administracion_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Administracion_DialogLayout.createSequentialGroup()
                                .addComponent(btn_CrearTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_BorrarTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Administracion_DialogLayout.createSequentialGroup()
                                .addComponent(btn_ModificarTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn_VisualizarTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Administracion_DialogLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton1)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        Administracion_DialogLayout.setVerticalGroup(
            Administracion_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Administracion_DialogLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Administracion_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CrearTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BorrarTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Administracion_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ModificarTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_VisualizarTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        VisualizarTorneo_Dia.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel4.setText("Torneo");

        TablaJornadaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipo Visita", "Peso Visita", "Equipo Casa", "Peso Casa", "Diferencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaJornadaA);

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel5.setText("Jornada B");

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel6.setText("Jornada A");

        btn_SalirVisualizacionTorneo.setText("Salir");
        btn_SalirVisualizacionTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirVisualizacionTorneoActionPerformed(evt);
            }
        });

        TablaJornadaB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipo Visita", "Peso Visita", "Equipo Casa", "Peso Casa", "Diferencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaJornadaB);

        javax.swing.GroupLayout VisualizarTorneo_DiaLayout = new javax.swing.GroupLayout(VisualizarTorneo_Dia.getContentPane());
        VisualizarTorneo_Dia.getContentPane().setLayout(VisualizarTorneo_DiaLayout);
        VisualizarTorneo_DiaLayout.setHorizontalGroup(
            VisualizarTorneo_DiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisualizarTorneo_DiaLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(262, 262, 262))
            .addGroup(VisualizarTorneo_DiaLayout.createSequentialGroup()
                .addGroup(VisualizarTorneo_DiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VisualizarTorneo_DiaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(VisualizarTorneo_DiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_SalirVisualizacionTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(VisualizarTorneo_DiaLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(VisualizarTorneo_DiaLayout.createSequentialGroup()
                        .addGap(526, 526, 526)
                        .addGroup(VisualizarTorneo_DiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VisualizarTorneo_DiaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane3});

        VisualizarTorneo_DiaLayout.setVerticalGroup(
            VisualizarTorneo_DiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisualizarTorneo_DiaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(VisualizarTorneo_DiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VisualizarTorneo_DiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btn_SalirVisualizacionTorneo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VisualizarTorneo_DiaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane3});

        btn_VerEquipos.setText("Ver Equipos");
        btn_VerEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerEquiposActionPerformed(evt);
            }
        });

        jButton2.setText("Quinela de la Jornada");

        jButton3.setText("Ver Torneo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel7.setText("JORNADA");

        label_NumJornadaUser_Main.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        label_NumJornadaUser_Main.setText("#");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addComponent(label_NumJornadaUser_Main)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btn_VerEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(label_NumJornadaUser_Main))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_VerEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout User_MainLayout = new javax.swing.GroupLayout(User_Main.getContentPane());
        User_Main.getContentPane().setLayout(User_MainLayout);
        User_MainLayout.setHorizontalGroup(
            User_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        User_MainLayout.setVerticalGroup(
            User_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setText("JORNADA");

        label_NumJornadaMenuApuestas.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        label_NumJornadaMenuApuestas.setText("#");

        rb_EquipoA.setText("Equipo A");
        rb_EquipoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_EquipoAActionPerformed(evt);
            }
        });

        rb_Empate.setText("Empate");

        rb_EquipoB.setText("Equipo B");

        btn_SiguentePartido.setText("Siguiente Partido");

        javax.swing.GroupLayout MenuApuestasLayout = new javax.swing.GroupLayout(MenuApuestas.getContentPane());
        MenuApuestas.getContentPane().setLayout(MenuApuestasLayout);
        MenuApuestasLayout.setHorizontalGroup(
            MenuApuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuApuestasLayout.createSequentialGroup()
                .addGroup(MenuApuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuApuestasLayout.createSequentialGroup()
                        .addGroup(MenuApuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuApuestasLayout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(label_NumJornadaMenuApuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuApuestasLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(rb_EquipoA)
                                .addGap(91, 91, 91)
                                .addComponent(rb_Empate)
                                .addGap(67, 67, 67)
                                .addComponent(rb_EquipoB)))
                        .addGap(0, 147, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuApuestasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_SiguentePartido)))
                .addContainerGap())
        );
        MenuApuestasLayout.setVerticalGroup(
            MenuApuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuApuestasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(MenuApuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(label_NumJornadaMenuApuestas))
                .addGap(105, 105, 105)
                .addGroup(MenuApuestasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_EquipoA)
                    .addComponent(rb_Empate)
                    .addComponent(rb_EquipoB))
                .addGap(18, 18, 18)
                .addComponent(btn_SiguentePartido)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel8.setText("Ingrese cuanto desea invertir en la quinela de la Jornada:");

        jButton4.setText("Confirmar Apuesta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(tf_MontoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton4)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(tf_MontoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton4)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Dialog_IngresarApuestaLayout = new javax.swing.GroupLayout(Dialog_IngresarApuesta.getContentPane());
        Dialog_IngresarApuesta.getContentPane().setLayout(Dialog_IngresarApuestaLayout);
        Dialog_IngresarApuestaLayout.setHorizontalGroup(
            Dialog_IngresarApuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Dialog_IngresarApuestaLayout.setVerticalGroup(
            Dialog_IngresarApuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quinela 2017");

        btn_admin.setText("Administración");
        btn_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adminMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel1.setText("Quinela 2017");

        btn_quinela.setText("Participación");
        btn_quinela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quinelaActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/fondo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(btn_quinela, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btn_quinela, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseClicked
        // TODO add your handling code here:
        Administracion_Dialog.setModal(true);
        Administracion_Dialog.pack();
        Administracion_Dialog.setLocationRelativeTo(this);
        Administracion_Dialog.setVisible(true);        
        this.setVisible(false);        
    }//GEN-LAST:event_btn_adminMouseClicked

    private void btn_VisualizarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VisualizarTorneoActionPerformed
        // TODO add your handling code here:
        if (torneo == null) {
            JOptionPane.showMessageDialog(this, "No existe ningún torneo.", "¡Error!", JOptionPane.ERROR_MESSAGE);

        } else {
            VisualizarTorneo_Dia.pack();
            VisualizarTorneo_Dia.setVisible(true);
            VisualizarTorneo_Dia.setModal(true);
            Administracion_Dialog.setVisible(false);

            ((DefaultTableModel) TablaJornadaA.getModel()).setRowCount(0);
            ((DefaultTableModel) TablaJornadaB.getModel()).setRowCount(0);

            for (Partido p : torneo.getJornadas().get(0).getPartidos()) {
                DefaultTableModel model = ((DefaultTableModel) TablaJornadaA.getModel());

                Object[] row = {p.getA().getNombreEquipo(), p.getA().getPeso(), p.getB().getNombreEquipo(), p.getB().getPeso(),
                    p.getA().getPeso() - p.getB().getPeso()};
                model.addRow(row);
            }

            for (Partido p : torneo.getJornadas().get(1).getPartidos()) {
                DefaultTableModel model = ((DefaultTableModel) TablaJornadaB.getModel());
                Object[] row = {p.getA().getNombreEquipo(), p.getA().getPeso(), p.getB().getNombreEquipo(), p.getB().getPeso(),
                    p.getA().getPeso() - p.getB().getPeso()};
                model.addRow(row);
            }

            
        }
    }//GEN-LAST:event_btn_VisualizarTorneoActionPerformed

    private void btn_BorrarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarTorneoActionPerformed
        // TODO add your handling code here:
        torneo = null;
        JOptionPane.showMessageDialog(this, "¡El torneo se ha borrado exitosamente!");
    }//GEN-LAST:event_btn_BorrarTorneoActionPerformed

    private void btn_CrearTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearTorneoActionPerformed
        // TODO add your handling code here:

        CrearEquipos();

        Collections.shuffle(equipos); //randomizar el orden de los equipos para asignarles partidos

        CrearPartidos();
        
      //  RedondearPesos();

        JOptionPane.showMessageDialog(this, "¡El torneo se ha creado aleatoriamente!");

    }//GEN-LAST:event_btn_CrearTorneoActionPerformed

    private void btn_SalirVisualizacionTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirVisualizacionTorneoActionPerformed
        // TODO add your handling code here:
        VisualizarTorneo_Dia.setVisible(false);
        //Administracion_Dialog.setVisible(true);
        this.setVisible(true);
        

    }//GEN-LAST:event_btn_SalirVisualizacionTorneoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.Administracion_Dialog.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_VerEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_VerEquiposActionPerformed

    private void rb_EquipoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_EquipoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_EquipoAActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (torneo == null) {
            JOptionPane.showMessageDialog(this, "No existe ningún torneo.", "¡Error!", JOptionPane.ERROR_MESSAGE);

        } else {
            VisualizarTorneo_Dia.pack();
            VisualizarTorneo_Dia.setVisible(true);
            VisualizarTorneo_Dia.setModal(true);
            Administracion_Dialog.setVisible(false);
            User_Main.setVisible(false);

            ((DefaultTableModel) TablaJornadaA.getModel()).setRowCount(0);
            ((DefaultTableModel) TablaJornadaB.getModel()).setRowCount(0);

            for (Partido p : torneo.getJornadas().get(0).getPartidos()) {
                DefaultTableModel model = ((DefaultTableModel) TablaJornadaA.getModel());

                Object[] row = {p.getA().getNombreEquipo(), p.getA().getPeso(), p.getB().getNombreEquipo(), p.getB().getPeso(),
                    p.getA().getPeso() - p.getB().getPeso()};
                model.addRow(row);
            }

            for (Partido p : torneo.getJornadas().get(1).getPartidos()) {
                DefaultTableModel model = ((DefaultTableModel) TablaJornadaB.getModel());
                Object[] row = {p.getA().getNombreEquipo(), p.getA().getPeso(), p.getB().getNombreEquipo(), p.getB().getPeso(),
                    p.getA().getPeso() - p.getB().getPeso()};
                model.addRow(row);
            }

            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_quinelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quinelaActionPerformed
        // TODO add your handling code here:
        
        User_Main.setModal(true);
        User_Main.pack();
        User_Main.setVisible(true);
        User_Main.setLocationRelativeTo(this);
        
        
        
        
        
    }//GEN-LAST:event_btn_quinelaActionPerformed

    public void CrearEquipos() {

        File file = null;
        BufferedReader br = null;
        FileReader fr = null;

        File Entrenadores = null;
        BufferedReader br2 = null;
        FileReader fr2 = null;

        try {
            file = new File("./src/Data/Jugadores.txt");
            fr = new FileReader(file);
            br = new BufferedReader(fr);

            Entrenadores = new File("./src/Data/Entrenadores.txt");
            fr2 = new FileReader(Entrenadores);
            br2 = new BufferedReader(fr2);

            String linea = "";
            String[] partes = new String[4];
            String nombre = "";
            int edad = 0;
            double peso = 0.0;
            double pesoEquipo = 0.0;
            String tipo = "";
            String nac = "";
            DateFormat df = new SimpleDateFormat("MM/dd/yyyy");

            int contador = 0;
            int PosicionEquipo = -1;
            while ((linea = br.readLine()) != null) { //para agregar jugadores
                partes = linea.split(";");
                nombre = partes[0];
                edad = Integer.parseInt(partes[1]);
                nac = partes[2];
                peso = Double.parseDouble(partes[3]);
                tipo = partes[4];

                Date date;

                date = df.parse(nac);

                Jugador jug = new Jugador(nombre, peso, date, edad);
                jug.setTipoJugador(tipo);

                if (contador == 11) {
                    contador = -5;
                }

                if (contador == 0) {
                    PosicionEquipo++;
                }

                pesoEquipo = equipos.get(PosicionEquipo).getPeso() + peso;

                equipos.get(PosicionEquipo).setPeso(pesoEquipo);
                equipos.get(PosicionEquipo).addJugador(jug);

                contador++;
            }

            linea = "";
            partes = new String[1];
            nombre = "";
            peso = 0.0;

            for (int i = 0; i < 30; i++) {
                linea = br2.readLine();
                partes = linea.split(";");

                Entrenador e = new Entrenador(partes[0], Double.parseDouble(partes[1]));

                Equipo eq = equipos.get(i);
                e.setEquipo(eq);
                
                eq.setTrainer(e);

                eq.setPeso(eq.getPeso() + e.getPesoEntrenador());
                

            }
            
        } catch (Exception e) {
            e.printStackTrace();
            try {
                br.close();
                fr.close();
                br2.close();
                fr2.close();
                
            } catch (IOException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }

    public void RedondearPesos() {
        for (Equipo equipo : equipos) {
            equipo.setPeso(Double.parseDouble(df.format(equipo.getPeso())));
        }
    }

    public void CrearPartidos() {

        Jornada jorn1 = new Jornada();
        Jornada jorn2 = new Jornada();
        
        Random r = new Random();

        for (int i = 0; i < 15; i++) {

            Partido par = new Partido();
            
            Equipo Casa = equipos.get((i * 2) + 1);
            Equipo Visita = equipos.get((i * 2));
            
            double pesoViejoB = Casa.getPeso(); //casa
            System.out.println("Casa(old): " + pesoViejoB);
            double pesoViejoA = Visita.getPeso(); //visita
            double aumento = 1.65 * (r.nextInt(20) + 1);
            
            par.setA(Visita); //i * 2 para conseguir siempre el equipo que va siguente
            Casa.setPeso(pesoViejoB + aumento); //aumentar el peso al equipo de casa
            par.setB(Casa);
            System.out.println("Casa(aumento): " + Casa.getPeso());

            par = AgregarArbitros(par, i * 4); //va a agregar cada cuatro nuevos arbitros a segun el i del for. i del for = numero de partido
            jorn1.addPartido(par);

            par = new Partido(); //reiniciar variable partido
            r = new Random();
            aumento = 1.65 * (r.nextInt(20) + 1);
            
            Casa.setPeso(pesoViejoB); //restarle el aumento al equipo de casa que ahora es visitante
            par.setA(Casa);
            Visita.setPeso(pesoViejoA + aumento);
            par.setB(Visita);

            par = AgregarArbitros(par, i * 4);
            System.out.println("Casa(old2): " + Casa.getPeso());
            jorn2.addPartido(par);

        }

        /*for (Partido par : jorn1.getPartidos()) {
            System.out.println(par.getA().getNombreEquipo() + " VS " + par.getB().getNombreEquipo());
            for (Arbitro arb : par.getArbitros()) {
                System.out.println(arb.getNombreArbitro());
            }
        }*/
        torneo = new Torneo();
        torneo.addJornada(jorn1);
        torneo.addJornada(jorn2);

    }

    public Partido AgregarArbitros(Partido par, int contador) {

        File file = null;
        BufferedReader br = null;
        FileReader fr = null;

        try {
            file = new File("./src/Data/Arbitros.txt");
            fr = new FileReader(file);
            br = new BufferedReader(fr);

            String linea = "";
            String[] partes = new String[2];
            String nombre = "";
            String tipo = "";
            double peso = 0.0;

            int contadorwhile = 0;

            for (int i = 0; i < contador; i++) {
                linea = br.readLine();
            }
            while ((linea = br.readLine()) != null) {

                partes = linea.split(";");
                nombre = partes[0];
                tipo = partes[1];
                peso = Double.parseDouble(partes[2]);

                Arbitro arb = new Arbitro(tipo, nombre, peso);

                arb.setPartido(par);

                par.addArbitro(arb);

                if (contadorwhile == 4) {
                    break;
                }

                contadorwhile++;

            }
        } catch (Exception e) {
            e.printStackTrace();
            
        } finally{
            try {
                br.close();
                fr.close();
            } catch (Exception e) {
            }
        }

        return par;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Administracion_Dialog;
    private javax.swing.JDialog Dialog_IngresarApuesta;
    private javax.swing.JDialog MenuApuestas;
    private javax.swing.JTable TablaJornadaA;
    private javax.swing.JTable TablaJornadaB;
    private javax.swing.JDialog User_Main;
    private javax.swing.JDialog VisualizarTorneo_Dia;
    private javax.swing.JButton btn_BorrarTorneo;
    private javax.swing.JButton btn_CrearTorneo;
    private javax.swing.JButton btn_ModificarTorneo;
    private javax.swing.JButton btn_SalirVisualizacionTorneo;
    private javax.swing.JButton btn_SiguentePartido;
    private javax.swing.JButton btn_VerEquipos;
    private javax.swing.JButton btn_VisualizarTorneo;
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_quinela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label_NumJornadaMenuApuestas;
    private javax.swing.JLabel label_NumJornadaUser_Main;
    private javax.swing.JRadioButton rb_Empate;
    private javax.swing.JRadioButton rb_EquipoA;
    private javax.swing.JRadioButton rb_EquipoB;
    private javax.swing.JTextField tf_MontoApuesta;
    // End of variables declaration//GEN-END:variables
}
